### ISSUE TITLE
Feature request: Recursive file showing

### ISSUE THREAD

**Issue by RaitaroH** [marvinkreis/rofi-file-browser-extended#10]
So I like the idea of the file browser. Unfortunately it only shows you one dir at a time in which case is pretty much like using some vifm/nnn/ranger kinda thing. 

My suggestion is: recursively show the files, such as in this case `ls -R $dir | rofi`

**Comment by marvinkreis** [comment]
I like this idea. I think it would also make sense to implement a depth limit until which subdirectories are shown. Otherwise it could be a bit overkill for slow hard drives.

Unfortunately, I don't have much time to implement this right now, but I will definitely come back to this, when I have some more time on my hands.

**Comment by marvinkreis** [comment]
Implemented in 2394a9953c3c80b5bc5b4f8e903a015d9a101b12.
